jobs:
- job: DeployPortainer
  displayName: 'Deploy Portainer to Kubernetes'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: KubernetesManifest@1
    inputs:
      action: 'deploy'
      connectionType: 'kubernetesServiceConnection'
      kubernetesServiceConnection: 'KubeAPI'
      manifests: '$(Build.SourcesDirectory)/manifests/portainer.yaml'
      options: '--validate=false'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(build.sourcesDirectory)'
      includeRootFolder: false

  - task: PublishBuildArtifacts@1

trigger:
- main
