apiVersion: apps/v1
kind: Deployment
metadata:
  name: faroapplication-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: faroapplication
  template:
    metadata:
      labels:
        app: faroapplication
    spec:
      containers:
      - name: faroapplication
        image: farotestregistry.azurecr.io/jebara7/helloworld:#{Build.BuildId}#
        ports:
        - containerPort: 5000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: faroapplication-svc
spec:
  selector:
    app: faroapplication
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
