apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: farosolutions-app
  template:
    metadata:
      labels:
        app: farosolutions-app
    spec:
      containers:
      - name: helloworld
        image: farotestregistry.azurecr.io/jebara7/helloworld:#{Build.BuildId}#
        ports:
        - containerPort: 5000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: farosolutions-app-svc
spec:
  selector:
    app: farosolutions-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
